GET http://localhost:4004/odata/v2/srv-api/Weapons

###

POST http://localhost:4004/odata/v2/srv-api/Weapons
Content-Type: application/json

{
    "Name": "PKM",
    "Manufacturer": "Kalashnikov Concern",
    "Model": "PKM",
    "Type": "Machine Gun",
    "Caliber": "7.62x54mmR",
    "Range": "1000 m",
    "Accuracy": "Medium-High",
    "BaseDamage": "95",
    "APDamage": "80",
    "Cost": "140000",
    "Weight": "7.5 kg"
  }
